### ISSUE TITLE
running time of build-rwr-diffusion

### ISSUE THREAD

**Issue by weizhu365** [stracquadaniolab/pygna#22]
Dear pygan developers; 

I have downloaded the latest biogrid data and tried to run generate shortest-path matrix using the command: 

pygna build-distance-matrix biogrid.txt biogrid_sp.hdf5

The biogrid.txt file has 547,720 rows.  The building process has already taken 4 days and it is still running.  Could you tell me how long it make take and whether there is any solution to speed it up.

Thanks,

Wei

**Comment by violafanfani** [comment]
Hi @weizhu365, sorry for the delayed reply. Is this still an issue?
